version: '3.9'

services:
  dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=katha-sansar
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
